server:
  port: 8201
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: circle-auth
          uri: lb://circle-auth
          predicates:
            - Path=/circle-auth/**
          filters:
            - StripPrefix=1
        - id: circle-main
          uri: lb://circle-main
          predicates:
            - Path=/circle-main/**
          filters:
            - StripPrefix=1
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"
      - "/actuator/**"
      - "/**/oauth/token"
      - "/**/rsa/publicKey"
      - "/**/user/login"
      - "/**/user/create"
      - "/**/user/getAuthCode"
      - "/**/user/"
      - "/**/article/getArticles"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
