server:
  port: 8201
  ssl:
    key-store: classpath:acircle.fun.pfx
    key-store-type: PKCS12
    enabled: true
    key-store-password: hzP7oATi
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: circle-auth
          uri: lb:http://circle-auth
          predicates:
            - Path=/circle-auth/**
          filters:
            - StripPrefix=1
        - id: circle-main
          uri: lb:http://circle-main
          predicates:
            - Path=/circle-main/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'https://acircle.fun:8201/circle-auth/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: localhost
    password:
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"
      - "/actuator/**"
      - "/**/oauth/token"
      - "/**/rsa/publicKey"
      - "/**/user/create"
      - "/**/user/login"
      - "/**/user/getAuthCode"
      - "/**/article/getHomeRecommendArticles"
      - "/**/article/getArticleDetailByArticleId/**"
      - "/**/article/getArticlesByUserId/**"
      - "/**/comment/getByArticleId/**"
      - "/**/like/get/**"
      - "/**/oss/getALiYunOSSToken"
      - "/**/esArticle/search"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
