server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/circle?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: redis # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  dubbo:
    application:
      name: leaf-consumer
    registry:
      address: zookeeper://zookeeper:2181
    scan: com.acircle.circle

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

redis:
  database: circle
  key:
    authCode: 'authCode'
    user: 'user'
  expire:
    authCode: 90 # 验证码超期时间
    common: 86400 # 24小时

aliyun:
  sts:
    EndPoint: sts.aliyuncs.com
    AccessKeyID: LTAI5tHCwix34d4Parpy5HA6 # 访问身份验证中用到用户标识
    AccessKeySecret: yuLTJgFIaGFWmrYj8PfpsW2T0xuHJJ # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    RoleArn: acs:ram::1366284796191670:role/oss-access-role
    PolicyFile: policy/bucket_write_policy.txt
    TokenExpireTime: 30

feign:
  okhttp:
    enabled: true
ribbon:
  ConnectTimeout: 3000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）

logging:
  level:
    com.acircle.circle.dao: DEBUG
    com.acircle.circle.mapper: DEBUG
